import Link from 'next/link';
import SchoolImage from '@/components/SchoolImage';
import Reveal from '@/components/Reveal';
import ArrowIcon from '@/components/ArrowIcon';
import StageCarousel from '@/components/StageCarousel';
import { pageMetadata } from '@/lib/seo';
export const metadata = pageMetadata('home');
const stages = [
  { number: '01', title: 'Early Years', meta: 'Crèche · Pre-School', text: 'Play, storytelling, early language and number skills.', href: '/academics/early-years' },
  { number: '02', title: 'Primary', meta: 'Elementary School', text: 'English, mathematics and science, alongside arts, music and physical education.', href: '/academics/primary' },
  { number: '03', title: 'Secondary', meta: 'Middle · High School', text: 'Subject depth and preparation for Cambridge and Nigerian examinations.', href: '/academics/secondary' },
];
export default function Home() {
 return <div className="home-page">
  <section className="hero" aria-labelledby="hero-title">
   <div className="hero-media"><SchoolImage src="/images/campus.jpg" alt="The buildings and landscaped grounds of MasterCare International School in Asaba" fill priority sizes="100vw" /></div><div className="hero-scrim" />
   <div className="shell hero-content"><p className="hero-kicker">MasterCare International School · Asaba, Nigeria</p><h1 id="hero-title">Raising<br /><span>global heroes.</span></h1><div className="hero-bottom"><p>From first discoveries to university preparation. A day and boarding school bringing together Nigerian and Cambridge learning, grounded in Christian values.</p><div className="hero-actions"><Link href="/admissions" className="pill-button light">Join our school <ArrowIcon size={18}/></Link><Link href="/contact#enquire" className="text-link light-link">Arrange a visit <ArrowIcon size={18}/></Link></div></div><div className="hero-facts"><span>Established 2014</span><span>Early Years · Primary · Secondary</span><span>Excellence through Christ</span></div></div>
  </section>
  <section className="welcome-school section-pad"><div className="shell welcome-grid"><Reveal><p className="eyebrow">Welcome to MasterCare</p><h2>An Asaba school.<br /><em>A world of ambition.</em></h2></Reveal><div><p className="welcome-lead">An education that begins with play and grows into purpose.</p><p>Founded in 2014, MCIS brings pre-school, primary and secondary education together on its Asaba campus. Students progress from language, number and creative discovery to subject specialisms and Cambridge and Nigerian examination pathways.</p><Link href="/discover" className="text-link">Discover our school <ArrowIcon size={18}/></Link></div></div><div className="shell school-at-glance"><span><b>2014</b>Our story begins</span><span><b>3</b>Stages of learning</span><span><b>Day & boarding</b>Ways to belong</span><span><b>Asaba</b>Our home in Delta State</span></div></section>
  <section id="learning" className="learning-section section-pad"><div className="shell"><Reveal className="section-heading split-heading"><div><p className="eyebrow">01 / The learning journey</p><h2>Small beginnings.<br /><em>Open possibilities.</em></h2></div><Link className="text-link" href="/academics">Explore academics <ArrowIcon size={18} /></Link></Reveal><StageCarousel stages={stages} /><div className="pathway-note"><p>Nigerian roots. International pathways.</p><Link href="/academics#pathways">Cambridge · IGCSE · WAEC · NECO · UTME <ArrowIcon size={16} /></Link></div></div></section>
  <section className="purpose-section section-pad"><div className="shell purpose-grid"><Reveal className="purpose-title"><p className="eyebrow light">02 / The MasterCare approach</p><h2>Great education<br />shapes <em>the person.</em></h2></Reveal><Reveal className="purpose-copy"><p>Learning matters. So does what students do with it.</p><p>MCIS brings Nigerian and international learning together with Christian values, mentorship and opportunities to take responsibility.</p><Link className="text-link light-link" href="/discover">What makes us MasterCare <ArrowIcon size={18} /></Link></Reveal><div className="purpose-values" aria-label="HEROES values">{['Heroes','Excellence','Responsibility','Order','Entrepreneurship','Solutions'].map(value => <span key={value}><b>{value[0]}</b>{value}</span>)}</div></div></section>
  <section className="campus-stories section-pad"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">03 / The places. The people. The possibilities.</p><h2>A school with<br /><em>stories to tell.</em></h2></div><Link href="/student-life" className="text-link">Life at MCIS <ArrowIcon size={18}/></Link></div><div className="story-grid"><article className="school-story"><Link href="/discover#heritage" className="story-image"><SchoolImage src="/images/archive-3.jpg" alt="Classroom block at MCIS at its commissioning, from the school development archive" fill sizes="(max-width: 600px) 100vw, 50vw"/></Link><div className="story-meta"><span>Campus development</span><span>From the archive</span></div><h3>More space for learning.</h3><p>A six-classroom block and library were donated to MCIS following teacher Felix Ariguzo’s 2017 Maltina Teacher of the Year recognition.</p><Link href="/discover#heritage" className="text-link">Read the school story <ArrowIcon size={17}/></Link><p className="image-credit">Archive photograph: <a href="https://www.nbplc.com/nigerian-breweries-fulfills-promise-to-maltina-teacher-of-the-year-donates-block-of-classrooms/">Nigerian Breweries</a></p></article><article className="school-story"><Link href="/student-life#sport" className="story-image"><SchoolImage src="/images/sport-2017.jpg" alt="MCIS football players celebrating their 2017 Delta State Principals’ Cup victory" fill sizes="(max-width: 600px) 100vw, 50vw"/></Link><div className="story-meta"><span>Sport & teamwork</span><span>2017 archive</span></div><h3>A team. A trophy. A shared memory.</h3><p>MCIS won the 2017 Delta State Principals’ Cup, beating Idjerhe Grammar School 2–1 in the final.</p><Link href="/student-life#sport" className="text-link">Explore life beyond lessons <ArrowIcon size={17}/></Link><p className="image-credit">Archive photograph: <a href="https://guardian.ng/sport/delta-to-ban-schools-without-sporting-facilities/">The Guardian Nigeria</a></p></article></div></div></section>
  <section className="learning-spaces section-pad"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">Inside the learning environment</p><h2>Ideas need room<br /><em>to grow.</em></h2></div><p className="heading-note">Explore the learning spaces and programmes described by the school, then see them for yourself on a campus visit.</p></div><div className="spaces-grid"><article><span>01 / Discover</span><h3>Science laboratories</h3><p>Spaces for practical science, investigation and connecting classroom ideas with observation.</p></article><article><span>02 / Read</span><h3>The school library</h3><p>A resource for reading, research and developing independent study habits.</p></article><article><span>03 / Create</span><h3>STEM & robotics</h3><p>Technology and problem-solving feature in the school’s published learning programme.</p></article></div><Link href="/contact#enquire" className="text-link">Explore the campus with us <ArrowIcon size={18}/></Link></div></section>
  <section className="home-admissions section-pad"><div className="shell home-admissions-grid"><Reveal><p className="eyebrow">04 / Your next chapter</p><h2>It starts with<br /><em>a conversation.</em></h2></Reveal><div><p>Choose a learning stage. Ask your questions. See the campus for yourself.</p><Link href="/admissions" className="pill-button">Explore admissions <ArrowIcon size={18} /></Link><Link href="/contact#enquire" className="text-link">Arrange a visit <ArrowIcon size={18} /></Link></div></div></section>
 </div>;
}
